### ISSUE TITLE
[Proposal] Testnet2 Record Epic

### ISSUE THREAD

**Issue by collinc97** [AleoHQ/aleo#75]
## 💥 Proposal

Requirements to add testnet2 record support to aleo sdk.

Tracking issue checklist:
- [x] implement datatypes
  - [x] record
  - [x] record ciphertext
- [x] implement wasm_bindgen methods
  - [x] record
  - [x] record ciphertext
- [ ] implement CLI support
  - [ ] record
  - [ ] record ciphertext
- [x] call JS methods in website frontend
  - [x] record
  - [x] record ciphertext

**Comment by collinc97** [comment]
Closed by #144
